---
title: "TNAO - Supplement"
author: "Sven Kleine Bardenhorst"
date: "14 12 2020"
output:
  rmdformats::material:
    highlight: kate
    thumbnails: true
    code_folding: show
    fig_width: 10
    fig_height: 6
    df_print: kable
---

```{css, echo = FALSE}
.header-panel {
    background-color: #940a21;
    min-height: 144px;
    position: relative;
    z-index: 3;
}

table.Rtable1 {
  color:black;
}

```


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r Load libraries, include=FALSE}
library(tidyverse)
library(haven)
library(Hmisc)
library(dplyr)
library(knitr)
library(table1)
library(DiagrammeR)
library(summarytools)
library(hablar)
library(labelled)
library(xtable)
library(huxtable)
library(corrplot)
library(sjPlot)
library(MASS)
library(kableExtra)
library(reshape2)
library("rgl")

st_options(bootstrap.css     = FALSE,       # Already part of the theme so no need for it
           plain.ascii       = FALSE,       # One of the essential settings
           style             = "rmarkdown", # Idem.
           dfSummary.silent  = TRUE,        # Suppresses messages about temporary files
           footnote          = NA,          # Keeping the results minimalistic
           subtitle.emphasis = FALSE,       # For the vignette theme, this gives
           headings = F)       
                                           
```


```{r Load data, include=FALSE}
mydata <- read_dta(file = "ship_2019_137_md_s2t0_20200327.dta")
#summary(mydata)
glimpse(mydata)
data <- mydata %>% dplyr::select(c("zz_nr","stool_dna_tma_cutc","stool_dna_tma_cnta","stool_dna_tma_grdh","omics_tma_tmao","omics_tma_choline","omics_tma_betaine","omics_tma_carnitine","stool_dna_tma_16s_rdna"))
#dataselall <- data %>%
#        filter(stool_dna_tma_cutc < 99975 | stool_dna_tma_cutc > 99999)  %>%
#        filter(stool_dna_tma_cnta < 99975 | stool_dna_tma_cnta > 99999) %>%
#        filter(stool_dna_tma_grdh < 99975 | stool_dna_tma_grdh > 99999) %>%
#        filter(omics_tma_tmao < 99975 | omics_tma_tmao > 99999)  %>%
#        filter(omics_tma_choline < 99975 | omics_tma_choline > 99999) %>%
#        filter(omics_tma_betaine < 99975 | omics_tma_betaine > 99999) %>%
#        filter(omics_tma_carnitine < 99975 | omics_tma_carnitine > 99999) 


#data %>% filter(stool_dna_tma_16s_rdna > 99975 | stool_dna_tma_16s_rdna < 99999) %>% summarize( cutc = sum(stool_dna_tma_cutc < 99975 | stool_dna_tma_cutc > 99999))

#select based on 16S as all have it
dataselall <- data %>% filter(stool_dna_tma_16s_rdna < 99975 | stool_dna_tma_16s_rdna > 99999)
#dataselall <- data

###change special coding to NAs
sel <- names(dataselall)
dataselall[sel] <- lapply(dataselall[sel], function(x) replace(x,x %in% 99975:99999, NA))



###get Proband_IDs
probands_zz_nr <- dataselall$zz_nr ### 425 Probands

###get SHIPdata
SHIPt <- read_dta(file = "ship_2016_114_md_t0_20200206.dta")
SHIPs0 <- read_dta(file = "ship_2016_114_md_s0_20200206.dta")
SHIPs2 <- read_dta(file = "ship_2016_114_md_s2_20200206.dta")

###select for probands
P_SHIPt <- SHIPt %>% filter(zz_nr %in% probands_zz_nr) ### 374 Probands
P_SHIPs2 <- SHIPs2 %>% filter(zz_nr %in% probands_zz_nr) ### 51 Probands
P_SHIPs0 <- SHIPs0 %>% filter(zz_nr %in% probands_zz_nr) ### 51 Probands > same as s2 but sampled 5 years earlier - probably leave out as too few for longitudinal analyses

###select for key variables and bind rows
P_SHIPt_var <- P_SHIPt %>% dplyr::select(c("zz_nr","SEX_SHIP_T0","AGE_SHIP_T0",
                                    "t0_alko_02", # Alohol
                                    "t0_rau_01", # Raucher
                                    "t0_ernaehr_01", # Fleisch
                                    "t0_ernaehr_07", # Reis 
                                    "t0_ernaehr_08", # Salat / Gemüse, roh 
                                    "t0_ernaehr_09", # Gemüse, gekocht 
                                    "t0_ernaehr_11", # Vollkornbrot 
                                    "t0_ernaehr_10", # Obst
                                    "t0_ernaehr_13",
                                    #"ffs_pattern_t0",
                                    #"ffs_t0",
                                    "t0_diab_02","t0_stro_02","t0_mi_02","cca_lmean","cca_rmean"))
P_SHIPs2_var <- P_SHIPs2 %>% dplyr::select(c("zz_nr","SEX_SHIP2","AGE_SHIP2",
                                      "s2_alko_02", # Alkohol
                                      "s2_rau_01", # Raucher
                                      "s2_ernaehr_01",
                                      "s2_ernaehr_07",
                                      "s2_ernaehr_08",
                                      "s2_ernaehr_09",
                                      "s2_ernaehr_11",
                                      "s2_ernaehr_10",
                                      "s2_ernaehr_13",
                                      #"ffs_pattern_s2",
                                      #"ffs_s2",
                                      "s2_diab_02","s2_stro_02","s2_mi_02","cca_lmean","cca_rmean"))

P_SHIPt_SHIP2_var <- rbind(as.matrix(P_SHIPt_var),as.matrix(P_SHIPs2_var)) %>% as_tibble()
P_SHIPt_SHIP2_var_tma <- P_SHIPt_SHIP2_var %>% left_join(dataselall)

###some cleaning
P_SHIPt_SHIP2_var_tma$t0_diab_02[P_SHIPt_SHIP2_var_tma$t0_diab_02 > 0] <- 1 # t0_diab_02 IST NUR INDIKATOR FÜR BEHANDLUNGSART
P_SHIPt_SHIP2_var_tma$t0_mi_02[P_SHIPt_SHIP2_var_tma$t0_mi_02 > 0] <- 1
P_SHIPt_SHIP2_var_tma$t0_stro_02[P_SHIPt_SHIP2_var_tma$t0_stro_02 > 0] <- 1

P_SHIPt_SHIP2_var_tma$t0_diab_02[is.na(P_SHIPt_SHIP2_var_tma$t0_diab_02)] <- 0
P_SHIPt_SHIP2_var_tma$t0_mi_02[is.na(P_SHIPt_SHIP2_var_tma$t0_mi_02)] <- 0
P_SHIPt_SHIP2_var_tma$t0_stro_02[is.na(P_SHIPt_SHIP2_var_tma$t0_stro_02)] <- 0

outliers <- function(model) {
     cooksd <- cooks.distance(model)
     plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
     abline(h = 4*mean(cooksd, na.rm=T), col="red")  # add cutoff line
     text(x=1:length(cooksd)+1, y=cooksd-mean(cooksd), labels=ifelse(cooksd>4*mean(cooksd, na.rm=T),names(cooksd),""), col="red")    
}

```

# Explore variables

```{r}
detect_limit_cnta <- min(P_SHIPt_SHIP2_var_tma$stool_dna_tma_cnta[P_SHIPt_SHIP2_var_tma$stool_dna_tma_cnta > 0])
detect_limit_grdh <- min(P_SHIPt_SHIP2_var_tma$stool_dna_tma_grdh[P_SHIPt_SHIP2_var_tma$stool_dna_tma_grdh > 0])

data <-  P_SHIPt_SHIP2_var_tma %>%
         transmute(zz_nr = zz_nr,
                   
                   meat = case_when(t0_ernaehr_01 == 1 ~ 4,  # Täglich Fleisch
                                    t0_ernaehr_01 == 4 ~ 3,
                                    t0_ernaehr_01 == 5 ~ 2,
                                    t0_ernaehr_01 == 6 ~ 1), # Nie oder fast nie Fleisch
                   eggs = case_when(t0_ernaehr_13 == 6 ~ 1,
                                    t0_ernaehr_13 == 5 ~ 2,
                                    t0_ernaehr_13 == 4 ~ 3,
                                    t0_ernaehr_13 == 3 ~ 4,
                                    t0_ernaehr_13 == 2 ~ 5,
                                    t0_ernaehr_13 == 1 ~ 6),
                   meat_cat = case_when(t0_ernaehr_01 == 1 ~ 1,
                                        t0_ernaehr_01 == 4 ~ 0,
                                        t0_ernaehr_01 == 5 ~ 0,
                                        t0_ernaehr_01 == 6 ~ 0),
          gender = case_when(SEX_SHIP_T0 == 2 ~ 0,  #Weiblich
                             SEX_SHIP_T0 == 1 ~ 1), # Männlich
          rdna = stool_dna_tma_16s_rdna,
          age = AGE_SHIP_T0,
          cutc = stool_dna_tma_cutc,
          cnta = case_when(stool_dna_tma_cnta > 0 ~ stool_dna_tma_cnta,
                           stool_dna_tma_cnta == 0 ~ detect_limit_cnta/sqrt(2)),
          grdh = case_when(stool_dna_tma_grdh > 0 ~ stool_dna_tma_grdh,
                           stool_dna_tma_grdh == 0 ~ detect_limit_grdh/sqrt(2)),
          tmao = omics_tma_tmao,
          choline = omics_tma_choline,
          betaine = omics_tma_betaine,
          carnitine = omics_tma_carnitine,
          IMT_mean = (cca_lmean+cca_rmean)/2,
          diabetes = t0_diab_02,
          stroke = t0_stro_02,
          mi = t0_mi_02,
          ID = zz_nr) %>%
          convert(fct(stroke,mi,diabetes)) %>%
          set_variable_labels(IMT_mean = "IMT_mean")# %>%
  #mutate(cutc = cutc/rdna,
  #      cnta = cnta/rdna,
  #     grdh = grdh/rdna)

```

```{r}
reverse_scale <- function(x) {abs((max(x)+1)-x)}
data <- data %>% left_join(P_SHIPt_SHIP2_var_tma)
data <- data %>% mutate(alcohol = reverse_scale(t0_alko_02),
                smoker = case_when(t0_rau_01 == 2 ~ 0,
                                   t0_rau_01 == 1 ~ 1),
                rice = reverse_scale(t0_ernaehr_07),
                salad = reverse_scale(t0_ernaehr_08),
                vegetables = reverse_scale(t0_ernaehr_09),
                full_grain = reverse_scale(t0_ernaehr_11),
                fruits = reverse_scale(t0_ernaehr_10))
```



```{r results="asis"}

# Molar masses to convert to µM
choline_mm <- 104.1708
betaine_mm <- 117.148
carnitine_mm <- 161.199
tmao_mm <- 75.10966


t1_dat <- data %>%
  dplyr::select(gender,meat_cat,age,betaine,choline,carnitine,grdh,cutc,cnta,tmao,fruits,salad,vegetables) %>%
  dplyr::mutate(Diet = factor(meat_cat,levels=c(0,1,2),labels=c("Vegetarian","Daily Meat","p-val")),
                Gender = factor(gender,levels=c(0,1),labels=c("Female","Male")),
                Betaine = betaine/betaine_mm,
                Choline = choline/choline_mm,
                Carnitine = carnitine/carnitine_mm,
                TMAO = tmao/tmao_mm,
                cntA = cnta/10^5,
                grdH = grdh/10^5,
                cutC = cutc/10^5,
                .keep = "unused")




table1::label(t1_dat$age) <- "Age"
units(t1_dat$Betaine) <- "µM"
units(t1_dat$Choline) <- "µM"
units(t1_dat$Carnitine) <- "µM"

units(t1_dat$grdH) <- "x10^5"
units(t1_dat$cntA) <- "x10^5"
units(t1_dat$cutC) <- "x10^5"



fit <- lm(log(t1_dat$Betaine)~t1_dat$Diet+t1_dat$age)

fit <- summary(fit)
fit$coefficients[2,4]

rndr <- function(x, name, ...) {
    if (length(x) == 0) {
        y <- t1_dat[[name]]
        s <- rep("", length(render.default(x=y, name=name, ...)))
        if (is.numeric(y)) {
            p <- summary(lm(log(y)~t1_dat$Diet+t1_dat$age))$coefficients[3,4] 
        } else {
            p <- chisq.test(table(y, droplevels(t1_dat$Diet)))$p.value
        }
        s[2] <- sub("<", "&lt;", format.pval(p, digits=3, eps=0.001))
        s
    } else {
        render.default(x=x, name=name, ...)
    }
}

rndr.strat <- function(label, n, ...) {
    ifelse(n==0, label, render.strat.default(label, n, ...))
}


table1(~Gender+age+Betaine+Carnitine+Choline+grdH+cntA+cutC+TMAO|Diet,
       render.missing = NULL,
       data = t1_dat,
       topclass="Rtable1-zebra Rtable1-shade Rtable1-times",
       render=rndr,
       render.strat = rndr.strat,
       droplevels = F)
```

```{r}
df <- t1_dat %>%
  mutate(tmao = log(TMAO),
         cutc = log(cutC),
         cnta = log(cntA),
         grdh = log(grdH),.keep = "unused")
         
summary(lm(tmao~grdh,data=df))
summary(lm(tmao~cnta,data=df))
summary(lm(tmao~cutc,data=df))

summary(lm(cnta~salad,data=df))
summary(lm(cutc~fruits,data=df))
summary(lm(cutc~vegetables,data=df))


# p-adj
summary(lm(cnta~salad+age,data=df))
summary(lm(cutc~fruits+age,data=df))
summary(lm(cutc~vegetables+age,data=df))

# p-adj
summary(lm(cnta~age,data=df))
summary(lm(cutc~age,data=df))
summary(lm(cutc~age,data=df))


## Age
summary(lm(age~Diet,data=df))
summary(lm(age~Diet,data=df))
summary(lm(age~Diet,data=df))



```

```{r}

summary(lm(log(Choline)~cutc,data=df))


```


## Age categorisation

- 18-35
- 36-65
- 65-80
- >80

```{r}
library(hrbrthemes)

t1_dat %>% 
  mutate(age_cat = case_when(age >= 18 & age <= 25 ~ "18-25", # Young adult
                             age >= 26 & age <= 35 ~ "26-35",
                              age >= 36 & age <= 55 ~ "36-55",
                              age >= 56 & age <= 65 ~ "56-65",
                              age >= 66  ~ "66+")) ->t1_dat # Middle aged
                              #age >= 80 ~ "80+"),.after="age") -> t1_dat # Aged 


t1 <- t1_dat %>% 
  mutate(grdH = round(grdH,2),
         cutC = round(cutC,2),
         cntA = round(cntA,2),
         Diet = droplevels(Diet)) %>%
table1::table1(~TMAO+Choline+Betaine+Carnitine+cutC+cntA+grdH+Diet+fruits+vegetables+salad|age_cat,data=.,
                      render.missing = NULL,
       topclass="Rtable1-zebra Rtable1-shade Rtable1-times",
       droplevels = F,
       overall = F)



t1kable(t1,booktabs=T) %>% kable_styling("striped")

p <- t1_dat %>%
  dplyr::select(-c(fruits,salad,vegetables,age)) %>%
  mutate("TMAO (µM)" = (TMAO),
         "cutC (x10^5)" = (cutC),
         "cntA (x10^5)" = (cntA),
         "grdH (x10^5)" = (grdH),
         "Carnitine (µM)" = Carnitine,
         "Betaine (µM)" = Betaine,
         "Choline (µM)" = Choline,
         
         .keep = "unused") %>%
  melt() %>%
  ggplot(aes(x=age_cat,y=value,fill=age_cat),data=.) +
  geom_boxplot() + 
  facet_wrap(~variable,scales="free",strip.position = "left") +
  scale_y_log10() +
  theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle=90)) +
  ylab(NULL) +
  xlab(NULL)

ggsave("Plots/age_cat_distributions.PDF",plot=p,device=cairo_pdf,width=210,height=297,units="mm",dpi=300)
ggsave("Plots/age_cat_distributions.tiff",plot=p,device="tiff",width=210,height=297,units="mm",dpi=300)
```

## 10% extreme TMAO

```{r}

t1_dat %>%
  dplyr::mutate(TMAO_cat = case_when(TMAO > quantile(TMAO,probs = c(.1,.9),na.rm=T)[2] ~ "10% highest TMAO",
                                     TMAO < quantile(TMAO,probs = c(.1,.9),na.rm=T)[1] ~ "10% lowest TMAO")) %>%
  mutate(TMAO_cat = fct_relevel(as.factor(TMAO_cat),c("10% lowest TMAO","10% highest TMAO"))) -> t1_dat


t1_dat %>%
  filter(!is.na(TMAO_cat)) %>%
  table1(~TMAO+Gender+age+Betaine+Carnitine+Choline+grdH+cntA+cutC|TMAO_cat,
       render.missing = NULL,
       data = .,
       topclass="Rtable1-zebra Rtable1-shade Rtable1-times",
       droplevels = F,
       overall = F)


p <- t1_dat %>%
  dplyr::select(-c(fruits,salad,vegetables,age,TMAO)) %>%
  filter(!is.na(TMAO_cat)) %>%
    mutate("cutC (x10^5)" = (cutC),
         "cntA (x10^5)" = (cntA),
         "grdH (x10^5)" = (grdH),
         "Carnitine (µM)" = Carnitine,
         "Betaine (µM)" = Betaine,
         "Choline (µM)" = Choline,
         .keep = "unused") %>%
  melt() %>%
  ggplot(aes(x=TMAO_cat,y=value,fill=TMAO_cat),data=.) +
  geom_boxplot() + 
  scale_y_log10() +
  facet_wrap(~variable,scales="free",strip.position = "left") +
  theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle=90),
        plot.title = element_text(size = 15, face = "bold")) +
  ylab(NULL) +
  xlab(NULL)

ggsave("Plots/extreme_TMAO_distributions.PDF",plot=p,device=cairo_pdf,width=210,height=297,units="mm",dpi=300)
ggsave("Plots/extreme_TMAO_distributions.tiff",plot=p,device="tiff",width=210,height=297,units="mm",dpi=300)
```

## Gender

```{r}

df <- t1_dat %>%
  mutate(tmao = log(TMAO),
         cutc = log(cutC),
         cnta = log(cntA),
         grdh = log(grdH),
         choline = log(Choline),
         betaine = log(Betaine),
         carnitine = log(Carnitine),.keep = "unused")


summary(lm(tmao~Gender,data=df))
summary(lm(tmao~Diet,data=df))

summary(lm(choline~Gender,data=df))
summary(lm(carnitine~Gender,data=df))
summary(lm(betaine~Gender,data=df))

summary(lm(cutc~Gender,data=df))
summary(lm(cnta~Gender,data=df))
summary(lm(grdh~Gender,data=df))

summary(lm(tmao~Gender*Diet,data=df))

summary(lm(choline~Gender+Diet,data=df))
summary(lm(carnitine~Gender+Diet,data=df))
summary(lm(betaine~Gender+Diet,data=df))

summary(lm(cutc~Gender+Diet+vegetables,data=df))
summary(lm(cnta~Gender+Diet,data=df))
summary(lm(grdh~Gender+Diet,data=df))

fit <- lm(grdh~Gender+Diet,data=df)
fit0 <- lm(grdh~1,data=df)
anova(fit0,fit,test="F")
summary(fit)
```


## Clinical parameter

```{r}
library(dagitty)

IMT_dag <- dagitty("dag{
                   age -> IMT_mean
                   age -> TMAO -> IMT_mean}")
  
plot(graphLayout(IMT_dag))  

adjustmentSets(IMT_dag,"age","IMT_mean",effect="direct")
  
```




```{r}

hist(log(data$IMT_mean),na.rm=T)

summary(lm(log(IMT_mean) ~ log(tmao),data=data ))

summary(lm(log(IMT_mean)~age,data=data))


df <- data %>%
  zap_labels() %>%
  mutate(age_cat = case_when(age >= 18 & age <= 25 ~ "18-25", # Young adult
                             age >= 26 & age <= 35 ~ "26-35",
                              age >= 36 & age <= 55 ~ "36-55",
                              age >= 56 & age <= 65 ~ "56-65",
                              age >= 66  ~ "66+"),
         tmao = tmao/tmao_mm)

res <- df %>%
  group_by(age_cat) %>%
  nest() %>%
  mutate(model= map(data, function(x) lm(log(IMT_mean) ~ log(tmao),data=x)),
         results = map(model,tidy)) %>%
  dplyr::select(results) %>%
  unnest(results) %>%
  dplyr::filter(term=="log(tmao)") %>%
  mutate(p.value = paste0("p =", round(p.value,3)))


#df <- df %>% left_join(res,by="age_cat") %>% mutate(p.value = paste0("p =", round(p.value,3)))



p <- ggplot(aes(x=tmao,y=IMT_mean,color=age_cat),data=df) +
  geom_jitter() +
  facet_grid(~age_cat) +
  geom_smooth(method="lm") +
  geom_text(aes(x=3,y=.35,label=p.value),color="black",data=res) +
  scale_x_log10() +
  scale_y_log10() +
  theme_minimal() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle=90),
        axis.text = element_text(size=9),
        axis.title = element_text(size=14),
        strip.text.x = element_text(size=14)) +
  xlab("TMAO (µM)") +
  ylab("IMT (mm)")



ggsave("Plots/TMAO_IMT_AGE.PDF",plot=p,device=cairo_pdf,width=200,height=100,units="mm",dpi=300)
ggsave("Plots/TMAO_IMT_AGE.tiff",plot=p,device="tiff",width=200,height=100,units="mm",dpi=300)


model <- df %>% 
  filter(age_cat == "66+") %>%
  rlm(log(IMT_mean) ~ log(tmao)+age,data=.) 


f.robftest(model,var="log(tmao)")



df %>% 
  filter(age_cat == "18-65") %>%
  rlm(log(IMT_mean) ~ log(tmao)+age,data=. ) %>% summary


summary(model)

library(broom)

df %>%
  group_by(age_cat) %>%
  nest() %>%
  mutate(model= map(data, function(x) lm(log(IMT_mean) ~ log(tmao),data=x)),
         results = map(model,tidy)) %>%
  dplyr::select(results) %>%
  unnest(results) %>%
  dplyr::filter(term=="log(tmao)")
```




## Gene abundances 
```{r}



```

